Working with Numpy

1.install numpy
2. imoort numpy
3. use numpy methods

In [14]:
!pip install numpy

In [15]:
import numpy as np

In [16]:
print(np.__version__)

2.0.2


In [17]:
array1d=np.array([1,2,3])
print(array1d)

[1 2 3]


In [18]:
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
array3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(array3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.full((2,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [23]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(0,15,4)

array([ 0,  4,  8, 12])

In [25]:
np.linspace(2,10,12)

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [26]:
np.random.rand(9,3)

array([[0.10132494, 0.72450167, 0.6061939 ],
       [0.20752874, 0.55971182, 0.4444297 ],
       [0.6247819 , 0.78438374, 0.38507139],
       [0.84030032, 0.25414902, 0.6984903 ],
       [0.18282126, 0.67632867, 0.447981  ],
       [0.08145835, 0.38152219, 0.73641109],
       [0.70902049, 0.83902318, 0.56821594],
       [0.1882169 , 0.2344105 , 0.98979536],
       [0.78009107, 0.99453749, 0.39739295]])

In [27]:
np.random.randn(3,3)

array([[-0.05221778,  1.01930141, -1.11677693],
       [ 0.07022265, -0.18025282, -0.48913379],
       [-0.28005151,  0.70040967, -1.61837246]])

In [28]:
np.random.randint(1,5,size=(4,4))

array([[2, 3, 3, 1],
       [3, 4, 1, 3],
       [4, 2, 2, 4],
       [4, 3, 1, 3]])

In [29]:
np.empty((3,5))

array([[8.60410678e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05133352e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.32404027e-322]])

In [30]:
arr= np.array([["a","b","c","d","e"],[1,2,3,4,5]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(2, 5)
2
10
<U21
84
840


In [31]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[2])
print(a[-1])

print(a[1:4])
print(a[:3])
print(a[::2])
print(a[::-1])

10
30
50
[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [32]:
m = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(m[0, 0])
print(m[1, 2])
print(m[0, :])
print(m[:, 1])
print(m[0:2, 1:3])


1
6
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


In [33]:
a = np.array([10, 25, 8, 42, 17])

mask = a > 15
print(mask)
print(a[mask])
print(a[a > 15])
print(a[[0, 3]])


[False  True False  True  True]
[25 42 17]
[25 42 17]
[10 42]


In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a + 10)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[11 12 13]


In [35]:
a = np.array([1.0, 4.0, 9.0, 16.0])

np.sqrt(a)
np.exp(a)
np.log(a)
np.log10(a)
np.sin(a)
np.abs(a)
np.floor(a)
np.ceil(a)
np.round(a, 2)

array([ 1.,  4.,  9., 16.])

In [36]:
m = np.array([[1, 2, 3],
               [4, 5, 6]])

np.sum(m)
np.sum(m, axis=0)
np.sum(m, axis=1)
np.mean(m)
np.median(m)
np.std(m)
np.var(m)
np.min(m)
np.max(m)
np.argmin(m)
np.argmax(m)


np.int64(5)

In [37]:
a = np.arange(12)
b = a.reshape(3, 4)
c = a.reshape(2, 2, 3)
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [38]:
b.flatten()
b.ravel()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
b.T
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.vstack([a, b])
np.hstack([a, b])
np.concatenate([a, b], axis=0)

arr = np.arange(12).reshape(4, 3)
np.vsplit(arr, 2)
np.hsplit(arr, 3)


[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]