DAY 1 of NLP

Step 1 — Lowercasing

In [ ]:
text = 'Hello! this is a SAMPLE E mail to check Iqra and Akila. are looking at screen'
text_lower= text.lower()
print(text_lower)



hello! this is a sample e mail to check iqra and akila. are looking at screen


Step 2 — Removing punctuation & special characters

In [ ]:
import re
text='Hello! this is a SAMPLE E mail to check Iqra and Akila. are looking at screen'
text_clean=re.sub(r'[^a-z]',' ',text)
print(text_clean)

 ello  this is a          mail to check  qra and  kila  are looking at screen


Step 3 — Stopword removal

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords',quiet=True)
stop_words=set(stopwords.words('english'))
text="I'm going to college today"
token=[]
for word in text.split():
  if word not in stop_words:
    token.append(word)
print(token)

["I'm", 'going', 'college', 'today']


Step 4 — Tokenisation

In [ ]:
import nltk
nltk.download('punkt',quiet=True)
sentence="do you love me?"
basic=sentence.split()
print('Basic split:',basic)


Basic split: ['do', 'you', 'love', 'me?']


Step 5 — Stemming vs Lemmatisation

In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet', quiet=True)
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
words = ['running', 'studies', 'better', 'caring', 'happily']
for word in words:
  stem = stemmer.stem(word)
  lemma = lemmatizer.lemmatize(word, pos='v')
  print(f'{word:12} | stem: {stem:10} | lemma: {lemma}')


running      | stem: run        | lemma: run
studies      | stem: studi      | lemma: study
better       | stem: better     | lemma: better
caring       | stem: care       | lemma: care
happily      | stem: happili    | lemma: happily


Complete pipeline in one function

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download(['stopwords', 'wordnet', 'punkt'], quiet=True)
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    # Step 1: Convert to lowercase
    text = text.lower()
    # Step 2: Remove punctuation and special characters
    text = re.sub(r'[^a-z ]', '', text)
    # Step 3: Tokenize
    tokens = text.split()
    # Step 4: Remove stopwords
    filtered_tokens = []
    for w in tokens:
        if w not in stop_words:
            filtered_tokens.append(w)

    tokens = filtered_tokens
    # Step 5: Lemmatize
    lemmatized_tokens = []
    for w in tokens:
        lemmatized_tokens.append(
            lemmatizer.lemmatize(w)
        )
    tokens = lemmatized_tokens
    # Convert list back to string
    return ' '.join(tokens)

# Test
print(preprocess('I am running to the stores to buy some groceries!'))

running store buy grocery


Bag of Words (BoW) — just count words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
emails = [
'cricket match cricket match cricket', # genuine fan
'free win money free win money win', # spam
'cricket match free win money cricket', # cricket spam
]
# CountVectorizer builds the vocab and counts automatically
cv = CountVectorizer()
X = cv.fit_transform(emails).toarray() # .toarray() makes it readable
print('Vocabulary:', cv.get_feature_names_out())
print('BoW matrix:')
print(X)


Vocabulary: ['cricket' 'free' 'match' 'money' 'win']
BoW matrix:
[[3 0 2 0 0]
 [0 2 0 2 3]
 [2 1 1 1 1]]


TF-IDF — reward rare, important words

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
emails = [
'cricket match cricket match cricket',
'free win money free win money win',
'cricket match free win money cricket',
]
tfidf = TfidfVectorizer(sublinear_tf=True, max_df=0.95, min_df=1)
X_tfidf = tfidf.fit_transform(emails).toarray()
print('Feature names:', tfidf.get_feature_names_out())
print('TF-IDF matrix (rounded):')
import numpy as np
print(np.round(X_tfidf, 3))


Feature names: ['cricket' 'free' 'match' 'money' 'win']
TF-IDF matrix (rounded):
[[0.778 0.    0.628 0.    0.   ]
 [0.    0.532 0.    0.532 0.659]
 [0.646 0.382 0.382 0.382 0.382]]
